"""Sweep key-validation thresholds and record what each panel reports.

Writes docs/threshold-selection.md. Run scripts/fetch_validation_data.py first
so the public panels are present; missing panels are skipped and noted.
"""

import json
import sys
from dataclasses import replace
from pathlib import Path

import numpy as np
import pandas as pd

from paneldx import KeyValidationPolicy, validate_key

ROOT = Path(__file__).resolve().parents[1]
VALIDATION = ROOT / "tests" / "validation"
OUT = ROOT / "docs" / "threshold-selection.md"

SWEEPS = {
    "weak_evidence_fraction": [0.05, 0.10, 0.15, 0.20, 0.30],
    "supported_evidence_fraction": [0.30, 0.40, 0.50, 0.60],
    "minimum_entities": [10, 15, 20, 30],
    "minimum_null_gap": [0.02, 0.05, 0.10],
    "invariant_violation_rate": [0.01, 0.02, 0.05, 0.10],
}


def synthetic_panel(n_entities=250, n_periods=4, seed=0):
    rng = np.random.default_rng(seed)
    birth_year = rng.integers(1950, 2000, n_entities)
    region = rng.integers(0, 5, n_entities)
    visits = rng.integers(5_000, 500_000, n_entities).astype(float)
    spend = rng.integers(1_000, 200_000, n_entities).astype(float)
    frames = []
    for t in range(n_periods):
        visits = visits + rng.integers(100, 8_000, n_entities)
        spend = spend + rng.integers(50, 4_000, n_entities)
        frames.append(
            pd.DataFrame(
                {
                    "uid": np.arange(n_entities),
                    "period": t,
                    "birth_year": birth_year,
                    "region": region,
                    "total_visits": visits,
                    "total_spend": spend,
                    "rating": rng.normal(4.0, 0.5, n_entities),
                }
            )
        )
    return pd.concat(frames, ignore_index=True)


def positional(df):
    out = df.sort_values(["period", "total_spend"], ascending=[True, False]).reset_index(drop=True)
    out["positional_id"] = out.groupby("period").cumcount()
    return out.drop(columns=["uid"])


def load_cases():
    external, development, missing = [], [], []
    for case in json.loads((VALIDATION / "panels.json").read_text()):
        path = VALIDATION / "data" / case["file"]
        if not path.exists():
            missing.append(case["name"])
            continue
        df = pd.read_csv(path).drop(columns=case.get("drop_columns", []))
        external.append((case["name"], df, case["key"], case["time"], "documented"))
    for seed in range(5):
        df = synthetic_panel(seed=seed)
        development.append((f"synthetic-{seed}", df, "uid", "period", "correct"))
        development.append(
            (f"positional-{seed}", positional(df), "positional_id", "period", "broken")
        )
    return external, development, missing


def run(cases, policy):
    return {
        name: validate_key(df, key, time, policy=policy).status for name, df, key, time, _ in cases
    }


def misses(cases, statuses):
    documented = sum(
        statuses[n] == "fail" for n, *_, kind in cases if kind in ("documented", "correct")
    )
    inconclusive = sum(statuses[n] == "inconclusive" for n, *_ in cases)
    broken_pass = sum(statuses[n] in ("pass", "warn") for n, *_, kind in cases if kind == "broken")
    return documented, inconclusive, broken_pass


HEADER = """# Threshold sensitivity

Generated by `scripts/threshold_sensitivity.py`; do not edit by hand.

The defaults in `paneldx.policy` were chosen retrospectively while developing
the rules on the synthetic generator used in the test suite. They have not been
calibrated on held-out data. This page records how the verdict on each
available panel changes as one threshold at a time is varied, with the others
at their defaults. It is a sensitivity record, not a calibration: the external
set is {n_external} public panels, far too few for error rates with meaningful
confidence intervals.

Two groups of cases are shown:

- **external**: public panels from `tests/validation/panels.json`, evaluated on
  their documented entity key. A `fail` here is a false negative.
- **development**: the synthetic generator with a correct key (`synthetic-*`,
  should pass) and the same panels re-keyed by within-period row position
  (`positional-*`, should fail). These are the fixtures the rules were
  developed against, so agreement with them is expected and proves little.

The `misses` columns count documented or correct keys reported as `fail`,
cases reported `inconclusive`, and broken keys reported as `pass` or `warn`.
"""


def main() -> int:
    external, development, missing = load_cases()
    cases = external + development
    lines = [HEADER.format(n_external=len(external))]
    if missing:
        lines.append(f"Missing panels (not fetched): {', '.join(missing)}.\n")

    for param, values in SWEEPS.items():
        default = getattr(KeyValidationPolicy(), param)
        lines.append(f"## `{param}` (default {default})\n")
        names = [n for n, *_ in cases]
        lines.append(
            "| value | "
            + " | ".join(names)
            + " | fail on documented/correct | inconclusive | broken not failed |"
        )
        lines.append("|---|" + "---|" * (len(names) + 3))
        for value in values:
            policy = replace(KeyValidationPolicy(), **{param: value})
            statuses = run(cases, policy)
            documented, inconclusive, broken_pass = misses(cases, statuses)
            label = f"**{value}**" if value == default else str(value)
            row = [statuses[n] for n in names]
            lines.append(
                f"| {label} | "
                + " | ".join(row)
                + f" | {documented} | {inconclusive} | {broken_pass} |"
            )
        lines.append("")

    OUT.write_text("\n".join(lines))
    n_dev = len(development)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(external)} external, {n_dev} development cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
