"""Sweep key-validation thresholds and record what each panel reports.

Writes docs/threshold-selection.md. Run scripts/fetch_validation_data.py first
so the public panels are present; missing panels are skipped and noted.

Every panel this touches is development data under validation/protocol/protocol.md, so
the output is a sensitivity record and never an accuracy result.
"""

from __future__ import annotations

import sys

import numpy as np
import pandas as pd

from paneldx import KeyValidationPolicy, validate_key
from validation.manifest import ROOT, load_manifest

OUT = ROOT / "docs" / "threshold-selection.md"

SWEEPS: dict[str, list[float]] = {
    "weak_evidence_fraction": [0.05, 0.10, 0.15, 0.20, 0.30],
    "supported_evidence_fraction": [0.30, 0.40, 0.50, 0.60],
    "minimum_entities": [10, 15, 20, 30],
    "minimum_null_gap": [0.02, 0.05, 0.10],
    "invariant_violation_rate": [0.01, 0.02, 0.05, 0.10],
}


def synthetic_panel(n_entities=250, n_periods=4, seed=0):
    rng = np.random.default_rng(seed)
    birth_year = rng.integers(1950, 2000, n_entities)
    region = rng.integers(0, 5, n_entities)
    visits = rng.integers(5_000, 500_000, n_entities).astype(float)
    spend = rng.integers(1_000, 200_000, n_entities).astype(float)
    frames = []
    for t in range(n_periods):
        visits = visits + rng.integers(100, 8_000, n_entities)
        spend = spend + rng.integers(50, 4_000, n_entities)
        frames.append(
            pd.DataFrame(
                {
                    "uid": np.arange(n_entities),
                    "period": t,
                    "birth_year": birth_year,
                    "region": region,
                    "total_visits": visits,
                    "total_spend": spend,
                    "rating": rng.normal(4.0, 0.5, n_entities),
                }
            )
        )
    return pd.concat(frames, ignore_index=True)


def positional(df):
    out = df.sort_values(["period", "total_spend"], ascending=[True, False]).reset_index(drop=True)
    out["positional_id"] = out.groupby("period").cumcount()
    return out.drop(columns=["uid"])


def _policy_with(param: str, value: float) -> KeyValidationPolicy:
    """A policy with one threshold replaced.

    Built field by field rather than with `replace`, because the sweep mixes an
    integer threshold with float ones and a keyword splat cannot be typed.
    """
    defaults = KeyValidationPolicy()
    fields = {name: getattr(defaults, name) for name in defaults.__dataclass_fields__}
    fields[param] = int(value) if isinstance(getattr(defaults, param), int) else float(value)
    return KeyValidationPolicy(**fields)


def load_cases():
    """Public panels first, then the synthetic fixtures. Both are development
    data; the split here is by provenance, not by evidential standing."""
    manifest = load_manifest()
    data = ROOT / manifest["download_directory"]
    public, synthetic, missing = [], [], []

    for dataset in list(manifest["datasets"]):
        # Held-out panels are registered, not evaluated. A sensitivity sweep is
        # an evaluation.
        if dataset["access"] != "public" or dataset["role"] == "held_out":
            continue
        path = data / dataset["file"]
        if not path.exists():
            missing.append(dataset["id"])
            continue
        df = pd.read_csv(path).drop(columns=dataset.get("drop_columns", []))
        public.append(
            (dataset["id"], df, dataset["entity_key"], dataset["time_column"], "documented")
        )

    for seed in range(5):
        df = synthetic_panel(seed=seed)
        synthetic.append((f"synthetic-{seed}", df, "uid", "period", "correct"))
        synthetic.append(
            (f"positional-{seed}", positional(df), "positional_id", "period", "broken")
        )
    return public, synthetic, missing


def run(cases, policy):
    return {
        name: validate_key(df, key, time, policy=policy).status for name, df, key, time, _ in cases
    }


def misses(cases, statuses):
    documented = sum(
        statuses[n] == "fail" for n, *_, kind in cases if kind in ("documented", "correct")
    )
    inconclusive = sum(statuses[n] == "inconclusive" for n, *_ in cases)
    broken_pass = sum(statuses[n] in ("pass", "warn") for n, *_, kind in cases if kind == "broken")
    return documented, inconclusive, broken_pass


HEADER = """# Threshold sensitivity

Generated by `scripts/threshold_sensitivity.py`; do not edit by hand.

This page records how the verdict on each available panel moves as one
threshold at a time is varied, with the others at their defaults.

One default is calibrated: `minimum_null_gap`, fitted on the calibration split
under the grid frozen in `validation/protocol/calibration_grid.json`. The rest were
chosen while developing the rules on the synthetic generator used in the test
suite.

It is a sensitivity record, not a calibration and not an accuracy measurement.
**Every case below is development or calibration data** under
[the validation protocol](../validation/protocol/protocol.md), and the held-out split is
not swept at all. Agreement here is expected and proves little. No error rate
may be computed from this table.

Two groups of cases are shown:

- **public**: the development and calibration panels in
  `validation/manifests/datasets.json`, evaluated on their documented entity key. That key
  is known correct independently of paneldx, so a `fail` here is a false
  rejection. The held-out split is not swept: a sweep is an evaluation.
- **synthetic**: the generator with a correct key (`synthetic-*`, should pass)
  and the same panels re-keyed by within-period row position (`positional-*`,
  which must never be accepted).

The last three columns count documented or correct keys reported as `fail`,
cases reported `inconclusive`, and broken keys reported as `pass` or `warn`.
Under 0.5.0 the first is expected to be zero everywhere: a shortage of evidence
is `inconclusive`, and only a contradiction produces `fail`. The third is the
one that distinguishes threshold settings.
"""


def main() -> int:
    public, synthetic, missing = load_cases()
    cases = public + synthetic
    lines = [HEADER.format(n_public=len(public))]
    if missing:
        lines.append(f"Missing panels (not fetched): {', '.join(missing)}.\n")

    for param, values in SWEEPS.items():
        default = getattr(KeyValidationPolicy(), param)
        lines.append(f"## `{param}` (default {default})\n")
        names = [n for n, *_ in cases]
        lines.append(
            "| value | "
            + " | ".join(names)
            + " | documented keys failed | inconclusive | broken accepted |"
        )
        lines.append("|---|" + "---|" * (len(names) + 3))
        for value in values:
            policy = _policy_with(param, value)
            statuses = run(cases, policy)
            documented, inconclusive, broken_pass = misses(cases, statuses)
            label = f"**{value}**" if value == default else str(value)
            row = [statuses[n] for n in names]
            lines.append(
                f"| {label} | "
                + " | ".join(row)
                + f" | {documented} | {inconclusive} | {broken_pass} |"
            )
        lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({len(public)} public, {len(synthetic)} synthetic cases)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
