"""Compare a benchmark run against a saved baseline run.

    python -m validation.harness.comparison

Writes comparison.md, comparison.json and comparison_changes.csv.gz to the
current run's directory. Refuses to proceed unless both runs cover the same
cases.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import json
import sys
from collections import Counter
from pathlib import Path

from validation.harness.cases import CASES_FILE
from validation.manifest import ROOT

RESULTS = ROOT / "validation" / "results" / "development"
BASELINE = RESULTS / "v0.4.0"
CURRENT = RESULTS / "current"
CHANGES_FILE = "comparison_changes.csv.gz"

KEY_FIELDS = ("dataset_id", "corruption", "level", "seed")


def load_cases(directory: Path) -> dict[tuple, dict]:
    path = directory / CASES_FILE
    if not path.exists():
        raise SystemExit(f"no {CASES_FILE} in {directory}")
    with gzip.open(path, "rt", newline="") as handle:
        return {tuple(row[f] for f in KEY_FIELDS): row for row in csv.DictReader(handle)}


def counts(rows, predicate) -> int:
    return sum(1 for row in rows if predicate(row))


def measure(cases: dict[tuple, dict]) -> dict:
    rows = list(cases.values())
    correct = [r for r in rows if r["expectation"] == "key_correct"]
    broken = [r for r in rows if r["expectation"] == "broken_key"]
    structural = [r for r in rows if r["expectation"] == "structural"]
    documented = [r for r in rows if r["corruption"] == "none"]
    runtimes = sorted(float(r["runtime_seconds"]) for r in rows)
    return {
        "documented_keys_failed": counts(documented, lambda r: r["status"] == "fail"),
        "documented_keys_inconclusive": counts(documented, lambda r: r["status"] == "inconclusive"),
        "documented_keys": len(documented),
        "correct_keys_failed": counts(correct, lambda r: r["status"] == "fail"),
        "correct_keys": len(correct),
        "corrupted_accepted": counts(broken, lambda r: r["status"] in ("pass", "warn")),
        "corrupted_stopped": counts(broken, lambda r: r["status"] in ("fail", "inconclusive")),
        "corrupted": len(broken),
        "contradictions_detected": counts(structural, lambda r: r["status"] == "fail"),
        "contradictions": len(structural),
        "median_runtime_seconds": runtimes[len(runtimes) // 2] if runtimes else None,
        "status_mix": dict(Counter(r["status"] for r in rows)),
    }


def changed_verdicts(before: dict, after: dict) -> list[dict]:
    out = []
    for identity, old in before.items():
        new = after.get(identity)
        if new is None or old["status"] == new["status"]:
            continue
        out.append(
            {
                "dataset_id": old["dataset_id"],
                "corruption": old["corruption"],
                "level": old["level"],
                "seed": old["seed"],
                "expectation": old["expectation"],
                "from": old["status"],
                "to": new["status"],
                "reason": new["reason"],
            }
        )
    return out


ROW = "| {measure} | {before} | {after} |"


def table(before: dict, after: dict) -> str:
    rows = [
        ("Correct keys failed", "correct_keys_failed", "correct_keys"),
        ("Documented keys failed", "documented_keys_failed", "documented_keys"),
        ("Documented keys inconclusive", "documented_keys_inconclusive", "documented_keys"),
        ("Corrupted keys accepted (pass/warn)", "corrupted_accepted", "corrupted"),
        ("Corrupted keys stopped (fail/inconclusive)", "corrupted_stopped", "corrupted"),
        ("Contradictions detected", "contradictions_detected", "contradictions"),
    ]
    lines = ["| Measure | 0.4.0 | 0.5.0 |", "|---|---:|---:|"]
    for label, field, total in rows:
        lines.append(
            ROW.format(
                measure=label,
                before=f"{before[field]} of {before[total]}",
                after=f"{after[field]} of {after[total]}",
            )
        )
    lines.append(
        ROW.format(
            measure="Median runtime (s)",
            before=f"{before['median_runtime_seconds']:.4f}",
            after=f"{after['median_runtime_seconds']:.4f}",
        )
    )
    return "\n".join(lines)


def _document(cases, before, after, changes, moves, baseline_env, current_env) -> str:
    """The human-readable comparison."""
    moved = "\n".join(f"| `{move}` | {n:,} |" for move, n in moves.most_common())
    return f"""# {baseline_env["paneldx_version"]} against {current_env["paneldx_version"]}

Generated by `validation/harness/comparison.py`; do not edit by hand.

Both runs cover the same {len(cases):,} cases on the same panels, under the
profile and seeds recorded in `environment.json`. Every panel is development or
calibration data, and both runs used `n_shuffles = {current_env["n_shuffles"]}`,
so this table describes a change in behaviour rather than an accuracy result.

- baseline: paneldx {baseline_env["paneldx_version"]}, profile {baseline_env["profile"]}
- current: paneldx {current_env["paneldx_version"]}, profile {current_env["profile"]}

{table(before, after)}

## What moved

{len(changes):,} of {len(cases):,} verdicts changed.

| Change | Cases |
|---|---:|
{moved}

Every change is recorded case by case in `{CHANGES_FILE}`, with the reason code
attached to it.
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--baseline", type=Path, default=BASELINE)
    parser.add_argument("--current", type=Path, default=CURRENT)
    args = parser.parse_args(argv)

    before_cases, after_cases = load_cases(args.baseline), load_cases(args.current)
    if set(before_cases) != set(after_cases):
        only_before = len(set(before_cases) - set(after_cases))
        only_after = len(set(after_cases) - set(before_cases))
        raise SystemExit(
            "the two runs do not cover the same cases "
            f"({only_before} only in the baseline, {only_after} only in the current run); "
            "a comparison across different case sets would not be one"
        )

    before, after = measure(before_cases), measure(after_cases)
    changes = changed_verdicts(before_cases, after_cases)
    moves = Counter(f"{c['from']} -> {c['to']}" for c in changes)

    baseline_env = json.loads((args.baseline / "environment.json").read_text())
    current_env = json.loads((args.current / "environment.json").read_text())

    document = _document(before_cases, before, after, changes, moves, baseline_env, current_env)
    (args.current / "comparison.md").write_text(document)
    (args.current / "comparison.json").write_text(
        json.dumps(
            {
                "baseline": {"environment": baseline_env, "measures": before},
                "current": {"environment": current_env, "measures": after},
                "cases": len(before_cases),
                "changed": len(changes),
                "moves": dict(moves),
                "changed_verdicts": CHANGES_FILE,
            },
            indent=2,
        )
        + "\n"
    )
    # One row per changed verdict, in the same gzipped form as cases.csv.gz.
    if changes:
        with gzip.open(args.current / CHANGES_FILE, "wt", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=list(changes[0]))
            writer.writeheader()
            writer.writerows(changes)
    print(f"{len(changes)} of {len(before_cases)} verdicts changed")
    for move, n in moves.most_common():
        print(f"  {move}: {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
